FROM amazoncorretto:17-alpine-jdk AS build
WORKDIR /opt/src
COPY pom.xml .
RUN apk add --no-cache maven
RUN mvn dependency:go-offline
COPY src src
RUN mvn package -Dmaven.test.skip=true spring-boot:repackage

FROM eclipse-temurin:17-jre-alpine
COPY --from=build /opt/src/target/api-service-0.0.1-SNAPSHOT.jar /opt/app.jar
ENTRYPOINT ["java","-jar","/opt/app.jar"]